name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Клонування коду
      - name: Checkout code
        uses: actions/checkout@v3

      # Крок 2: Встановлення Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Крок 3: Встановлення залежностей для invoice
      - name: Install invoice dependencies
        working-directory: invoice
        run: npm install --legacy-peer-deps

      # Крок 4: Встановлення залежностей для discount
      - name: Install discount dependencies
        working-directory: generatePurchases
        run: npm install --legacy-peer-deps

      # Крок 5: Архівація invoice функції
      - name: Zip invoiceLambda
        run: |
          cd invoice
          zip -r ../invoice.zip . -x "*.test.js" "package-lock.json"

      # Крок 6: Архівація discount функції
      - name: Zip discountImageLambda
        run: |
          cd generatePurchases
          zip -r ../generatePurchases.zip . -x "*.test.js" "package-lock.json"

      # Крок 7: Налаштування AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Крок 8: Деплой generateInvoice Lambda
      - name: Deploy generateInvoice function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-north-1:652728306101:function:generateInvoice \
            --zip-file fileb://invoice.zip

      # Крок 9: Деплой generateDiscountImage Lambda
      - name: Deploy generatePurchases function
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-north-1:652728306101:function:generatePurchase \
            --zip-file fileb://generatePurchases.zip
